CC = gcc
CFLAGS = -Wall -O2 -I .

PROGS = show-bytes\
	logic \
	bisbic \
	sum\
	extend\
	bad-sum\
	inplace-swap.o\
	casting.o\
	uhp-ans.o\
	rbyte-ans.o\
	rshift-templates.o\
	puzzle.o\
	floatge-template.o\
	wordsize\
	printf\


all: $(PROGS)

clean:
	rm -f $(PROGS) *.o *~


